services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: projeto-api

    ports:
      - "5207:5207"

    environment:
      DB_SERVER: "${DB_SERVER}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"

      JWT_KEY: "${JWT_KEY}"
      JWT_ISSUER: "${JWT_ISSUER}"
      JWT_AUDIENCE: "${JWT_AUDIENCE}"

    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.4

    container_name: projeto-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ProjetoMultidiciplinar

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -proot --silent"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

volumes:
  mysql_data: