// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoMultidiciplinar.Data;

#nullable disable

namespace ProjetoMultidiciplinar.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915130855_Products model properties addition certo")]
    partial class Productsmodelpropertiesadditioncerto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProjetoMultidiciplinar.Models.ConversationsModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("ProjetoMultidiciplinar.Models.MessagesModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ConversationsModelID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UsersModelID")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("ConversationsModelID");

                    b.HasIndex("UsersModelID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ProjetoMultidiciplinar.Models.PhotosModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductsModelID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("ProductsModelID");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("ProjetoMultidiciplinar.Models.ProductsModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UsersModelID")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("UsersModelID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProjetoMultidiciplinar.Models.UsersModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rating")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjetoMultidiciplinar.Models.MessagesModel", b =>
                {
                    b.HasOne("ProjetoMultidiciplinar.Models.ConversationsModel", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationsModelID");

                    b.HasOne("ProjetoMultidiciplinar.Models.UsersModel", null)
                        .WithMany("Messages")
                        .HasForeignKey("UsersModelID");
                });

            modelBuilder.Entity("ProjetoMultidiciplinar.Models.PhotosModel", b =>
                {
                    b.HasOne("ProjetoMultidiciplinar.Models.ProductsModel", null)
                        .WithMany("Photos")
                        .HasForeignKey("ProductsModelID");
                });

            modelBuilder.Entity("ProjetoMultidiciplinar.Models.ProductsModel", b =>
                {
                    b.HasOne("ProjetoMultidiciplinar.Models.UsersModel", null)
                        .WithMany("Announcements")
                        .HasForeignKey("UsersModelID");
                });

            modelBuilder.Entity("ProjetoMultidiciplinar.Models.ConversationsModel", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ProjetoMultidiciplinar.Models.ProductsModel", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("ProjetoMultidiciplinar.Models.UsersModel", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
